name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Orchestrator
        run: cargo build --all --verbose
      - name: Run Orchestrator tests
        run: cargo test --all --verbose
